<a href="https://colab.research.google.com/github/ZeynepAkkus/Assigments/blob/main/C9195-Zeynep-Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [12]:
samples =np.random.normal(loc=100,scale=15,size=1000)
samples

array([ 79.24784399,  98.37754169, 104.05798555, 107.85680154,
        94.5336688 , 120.29333284,  95.852101  ,  94.9526276 ,
        95.42900851, 101.68246144, 104.20741063,  92.2981856 ,
        91.91187549,  95.50257068, 107.19189929,  85.72965998,
        77.20411816,  95.75274537,  96.53559198, 100.91457459,
        89.4730086 , 120.84020706,  74.26455191,  99.28355019,
        81.28313391, 109.86992929,  95.48693117,  89.10566578,
       112.07197392,  72.03407347,  79.9479398 ,  86.95785128,
       116.70905561,  96.4409898 ,  97.56230617,  72.74044788,
       103.18663346,  97.0106228 ,  90.42381621,  94.46408723,
       125.24818764, 118.5197774 , 122.26880655, 108.07370545,
        91.07594336,  97.66056809,  91.59417333,  95.17172398,
        86.84778609,  97.28200241,  79.43141208,  77.43216666,
        94.08452387,  88.5103368 , 101.86642201, 122.96755142,
        93.78391693,  98.75115694,  92.9169191 , 107.47552809,
       138.79929014,  87.31871037,  80.77025632, 111.43

Compute the **mean**, **median**, and **mode**

In [13]:
mean = np.mean(samples)
mean


99.60009580816022

In [14]:
median = np.median(samples)
median


99.52908083446428

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [16]:
min =  samples.min()
min

45.13433841574197

In [17]:
max = samples.max()
max

157.16882707449554

In [19]:
q1= np.percentile(samples, 25)
q1

89.11077964656403

In [52]:
q2=np.percentile(samples,50) == np.median(samples)
q2

True

In [21]:
q3=np.percentile(samples, 75)
q3

110.0179448489042

In [24]:
igr=q3-q1
igr

20.907165202340167

In [53]:
stats.iqr(samples)

20.907165202340167

Compute the **variance** and **standard deviation**

In [26]:
import statistics

In [27]:
variance = statistics.mean(samples)
variance


99.60009580816022

In [46]:
np.std(samples)

15.274355840190548

In [49]:
stats.mode(samples)

ModeResult(mode=array([45.13433842]), count=array([1]))

Compute the **skewness** and **kurtosis**

In [48]:
skewness = stats.skew(samples)
skewness


0.01812440880472413

In [56]:
kurtosis = kurtosis(samples)
kurtosis

NameError: ignored

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [36]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [41]:
y = np.random.randint(0,100,size=10)
y

array([96, 27, 90, 17, 66, 33, 85, 10, 36, 65])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [57]:
numer = len(x)*sum(x*y) - sum(x)*sum(y)
numer

-2225

In [58]:
denom = np.sqrt((len(x)*sum(x**2)-sum(x)**2)*(len(y)*sum(y**2)-sum(y)**2))
denom

8646.71180276063

In [59]:
r = numer/denom
r

-0.25732325197766226

## Pandas Correlation Calculation

Run the code below

In [61]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
x
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [62]:
r, p = stats.pearsonr(x, y)
r

0.758640289091187

In [63]:
stats.pearsonr(x,y)

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [65]:
rho =stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [81]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [67]:
tips = sns.load_dataset("tips")

In [69]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [76]:
stats.describe(tips)

DescribeResult(nobs=244, minmax=(1.0, 10.0), mean=2.99827868852459, variance=1.914454638062471, skewness=1.4564266884221506, kurtosis=3.5495519893455114)

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
?